### ISSUE TITLE
tecoble 이전으로 기존 댓글 동기화 필요

### ISSUE THREAD

**Issue by wannte** [woowacourse/tecoble#416]
[Javable Comments](https://github.com/woowacourse/javable-comments)

github issue로 관리되고 있는 부분의 동기화 필요. 설정파일도 확인이 필요할 것 같습니다.

**Comment by devJang** [comment]
OMG…

**Comment by TaewanKimmmm** [comment]
해결되었으므로 이슈 닫겠습니다~🙏
