### ISSUE TITLE
[오렌지] 자원 사용 후에는 해제를 꼭 하자(try-with-resource 를 사용해보자)

### ISSUE THREAD

**Issue by YerinCho** [woowacourse/tecoble#72]
처음 dao를 접해 사용해보면, 커넥션을 하고 close()를 해 주지 않은 경우가 있습니다.
이 때 try-with-resourse 를 사용하면 손쉽게 닫아줄 수 있다는 리뷰가 많이 있었습니다.

[관련리뷰](https://github.com/woowacourse/java-chess/pull/23#discussion_r298203305)

**Comment by hybeom0720** [comment]
해당 내용 3기 Tecoble에서 다루게 되었습니다! 이슈 닫겠습니다.
